### ISSUE TITLE
Support for process attachment?

### ISSUE THREAD

**Issue by voltechs** [david942j/gdb-ruby#55] opened 2019-06-28 20:36 UTC
Hi David,

I'm really interested in the project! Does `GDB::Ruby` allow for attaching to a running process (as `gdb` does), and if not, are there plans for that? This would be incredibly powerful with regards to debugging running processes, such as those in a production environment.

**Comment by david942j** [comment] 2019-06-29 05:08
What's your expected usage of attaching?
If you use the CLI gdb-ruby, it should work as normal gdb and therefore be able to attach a running process.

If you are writing a Ruby script and want to do something like: `gdb.attach(pid)`, then it do have a problem.
The problem is when attaching a non-stop process, `GDB::Ruby` will hang and wait for the gdb prompt (so it knows it can send the next command).
Some workarounds exist:
1. Use gdbserver to run your target process. I haven't try but I remember in this way the process will stop on the first instruction after gdb attached.
2. Prepare breakpoints which can be hit after gdb attached.
3. Send an interrupt signal to your target process before/after gdb attached

The third option might be a possible way to approve GDB::Ruby that send a signal to the target process on attaching.

What do you think?

**Comment by david942j** [comment] 2019-08-01 05:33
I'll close this issue if no further comments

**Closed** 2019-08-03 14:37 UTC
